# DATA

In [3]:
with open('data/AliceInWonderland_Ch01.txt', 'r', encoding = 'utf-8') as f:
    docs = f.read()

In [4]:
# total karakter
print("Total karakter:", len(docs))

Total karakter: 11385


# Token Awal

In [5]:
from nltk.tokenize import word_tokenize
token_awal = word_tokenize(docs)
print("Token awal:", len(token_awal))

Token awal: 2615


# REMOVE PUNCTUATION

In [6]:
import string

In [7]:
# hapus titik, koma, dan tanda baca lainnya
new_docs = docs.translate(str.maketrans('', '', string.punctuation))

print(new_docs[:5000])

Alice was beginning to get very tired of sitting by her sister on the
bank and of having nothing to do once or twice she had peeped into
the book her sister was reading but it had no pictures or
conversations in it “and what is the use of a book” thought Alice
“without pictures or conversations”

So she was considering in her own mind as well as she could for the
hot day made her feel very sleepy and stupid whether the pleasure of
making a daisychain would be worth the trouble of getting up and
picking the daisies when suddenly a White Rabbit with pink eyes ran
close by her

There was nothing so very remarkable in that nor did Alice think it
so very much out of the way to hear the Rabbit say to itself “Oh
dear Oh dear I shall be late” when she thought it over afterwards
it occurred to her that she ought to have wondered at this but at the
time it all seemed quite natural but when the Rabbit actually took a
watch out of its waistcoatpocket and looked at it and then hurried
on Alice star

“without pictures or conversations” dsb, tidak ikut dibersihkan karena bukan ASCII 

In [8]:
import re

In [9]:
# hapus tanda baca yang lain 
# termasuk yang bukan ASCII
new_docs = re.sub(r'[^\w\s]', '', new_docs)
print(new_docs[:5000])

Alice was beginning to get very tired of sitting by her sister on the
bank and of having nothing to do once or twice she had peeped into
the book her sister was reading but it had no pictures or
conversations in it and what is the use of a book thought Alice
without pictures or conversations

So she was considering in her own mind as well as she could for the
hot day made her feel very sleepy and stupid whether the pleasure of
making a daisychain would be worth the trouble of getting up and
picking the daisies when suddenly a White Rabbit with pink eyes ran
close by her

There was nothing so very remarkable in that nor did Alice think it
so very much out of the way to hear the Rabbit say to itself Oh
dear Oh dear I shall be late when she thought it over afterwards
it occurred to her that she ought to have wondered at this but at the
time it all seemed quite natural but when the Rabbit actually took a
watch out of its waistcoatpocket and looked at it and then hurried
on Alice started to

# STOPWORDS

Kata yang berdiri sendiri dan tidak ada maknanya, seperti kata hubung

In [10]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [11]:
# import english stopwords
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# gunakan stopwords bahasa inggris
stop_words = set(stopwords.words('english'))

# tokenisasi
word_tokens = word_tokenize(new_docs)

In [12]:
# apply stopword 
filtered_docs = [word for word in word_tokens if not word.lower() in stop_words]

In [13]:
# print
print(" ".join(filtered_docs[:200]))

Alice beginning get tired sitting sister bank nothing twice peeped book sister reading pictures conversations use book thought Alice without pictures conversations considering mind well could hot day made feel sleepy stupid whether pleasure making daisychain would worth trouble getting picking daisies suddenly White Rabbit pink eyes ran close nothing remarkable Alice think much way hear Rabbit say Oh dear Oh dear shall late thought afterwards occurred ought wondered time seemed quite natural Rabbit actually took watch waistcoatpocket looked hurried Alice started feet flashed across mind never seen rabbit either waistcoatpocket watch take burning curiosity ran across field fortunately time see pop large rabbithole hedge another moment went Alice never considering world get rabbithole went straight like tunnel way dipped suddenly suddenly Alice moment think stopping found falling deep well Either well deep fell slowly plenty time went look wonder going happen next First tried look make c

Kata seperti 'was' dihapus

# LOWERCASE

In [14]:
# mengubaah teks di filtered_docs menjadi lower semua
# karena bentuknya list maka gunakan list comprehension
lowered_docs = [word.lower() for word in filtered_docs]
print(lowered_docs[:5000])

['alice', 'beginning', 'get', 'tired', 'sitting', 'sister', 'bank', 'nothing', 'twice', 'peeped', 'book', 'sister', 'reading', 'pictures', 'conversations', 'use', 'book', 'thought', 'alice', 'without', 'pictures', 'conversations', 'considering', 'mind', 'well', 'could', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisychain', 'would', 'worth', 'trouble', 'getting', 'picking', 'daisies', 'suddenly', 'white', 'rabbit', 'pink', 'eyes', 'ran', 'close', 'nothing', 'remarkable', 'alice', 'think', 'much', 'way', 'hear', 'rabbit', 'say', 'oh', 'dear', 'oh', 'dear', 'shall', 'late', 'thought', 'afterwards', 'occurred', 'ought', 'wondered', 'time', 'seemed', 'quite', 'natural', 'rabbit', 'actually', 'took', 'watch', 'waistcoatpocket', 'looked', 'hurried', 'alice', 'started', 'feet', 'flashed', 'across', 'mind', 'never', 'seen', 'rabbit', 'either', 'waistcoatpocket', 'watch', 'take', 'burning', 'curiosity', 'ran', 'across', 'field', 'fortunately', 'time', '

In [15]:
# mengubah teks menjadi lower semua
lowered_docs = filtered_docs.lower()
print(lowered_docs[:5000])

AttributeError: 'list' object has no attribute 'lower'

In [16]:
# untuk checkpoint, simpan hasil preprocessing ke file
with open('data/preprocessed_AliceInWonderland_Ch01.txt', 'w', encoding = 'utf-8') as f:
    f.write(" ".join(filtered_docs))

# TRANSFORMERS

Untuk transformers lanjut di collab

# STEMMING

In [17]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps = PorterStemmer()

In [18]:
# karena bentuknya list maka gunakan list comprehension
# tokenisasi dulu
words = word_tokenize(" ".join(lowered_docs))

In [19]:
new_text = []
for w in words:
    new_text.append(ps.stem(w))

print(" ".join(new_text[:500]))

alic begin get tire sit sister bank noth twice peep book sister read pictur convers use book thought alic without pictur convers consid mind well could hot day made feel sleepi stupid whether pleasur make daisychain would worth troubl get pick daisi suddenli white rabbit pink eye ran close noth remark alic think much way hear rabbit say oh dear oh dear shall late thought afterward occur ought wonder time seem quit natur rabbit actual took watch waistcoatpocket look hurri alic start feet flash across mind never seen rabbit either waistcoatpocket watch take burn curios ran across field fortun time see pop larg rabbithol hedg anoth moment went alic never consid world get rabbithol went straight like tunnel way dip suddenli suddenli alic moment think stop found fall deep well either well deep fell slowli plenti time went look wonder go happen next first tri look make come dark see anyth look side well notic fill cupboard bookshelv saw map pictur hung upon peg took jar one shelv pass label 

# LEMMATIZATION

In [20]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [21]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

wnl = WordNetLemmatizer()

In [22]:
words = word_tokenize(" ".join(lowered_docs))
new_text = " ".join([wnl.lemmatize(w) for w in words])
print(new_text[:500])

alice beginning get tired sitting sister bank nothing twice peeped book sister reading picture conversation use book thought alice without picture conversation considering mind well could hot day made feel sleepy stupid whether pleasure making daisychain would worth trouble getting picking daisy suddenly white rabbit pink eye ran close nothing remarkable alice think much way hear rabbit say oh dear oh dear shall late thought afterwards occurred ought wondered time seemed quite natural rabbit act


# TOKENIZATION

In [23]:
# tokenisasi
data_tokenized = word_tokenize(" ".join(lowered_docs))
print(data_tokenized[:500])

['alice', 'beginning', 'get', 'tired', 'sitting', 'sister', 'bank', 'nothing', 'twice', 'peeped', 'book', 'sister', 'reading', 'pictures', 'conversations', 'use', 'book', 'thought', 'alice', 'without', 'pictures', 'conversations', 'considering', 'mind', 'well', 'could', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisychain', 'would', 'worth', 'trouble', 'getting', 'picking', 'daisies', 'suddenly', 'white', 'rabbit', 'pink', 'eyes', 'ran', 'close', 'nothing', 'remarkable', 'alice', 'think', 'much', 'way', 'hear', 'rabbit', 'say', 'oh', 'dear', 'oh', 'dear', 'shall', 'late', 'thought', 'afterwards', 'occurred', 'ought', 'wondered', 'time', 'seemed', 'quite', 'natural', 'rabbit', 'actually', 'took', 'watch', 'waistcoatpocket', 'looked', 'hurried', 'alice', 'started', 'feet', 'flashed', 'across', 'mind', 'never', 'seen', 'rabbit', 'either', 'waistcoatpocket', 'watch', 'take', 'burning', 'curiosity', 'ran', 'across', 'field', 'fortunately', 'time', '

# token terakhir

In [24]:
len(data_tokenized)

977

# TEXT VECTORIZATION

## OneHotEncoder

### Example

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import string

In [28]:
documents = [
    "The cat sat on the mat",
    "The dog sat on the log",
    "Cats and dogs are great pets."
]

words = [word.lower().strip(string.punctuation) for doc in documents for word in doc.split()]

vocabulary = sorted(set(words))

encoder = OneHotEncoder(sparse_output=False)
one_hot_vectors = encoder.fit_transform(np.array(vocabulary).reshape(-1, 1))

word_to_onehot = {vocabulary[i]: one_hot_vectors[i] for i in range(len(vocabulary))}

for word, vector in word_to_onehot.items():
    print(f"Word: {word}, One Hot Encoding: {vector}")

Word: and, One Hot Encoding: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Word: are, One Hot Encoding: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Word: cat, One Hot Encoding: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Word: cats, One Hot Encoding: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Word: dog, One Hot Encoding: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Word: dogs, One Hot Encoding: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Word: great, One Hot Encoding: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Word: log, One Hot Encoding: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Word: mat, One Hot Encoding: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Word: on, One Hot Encoding: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Word: pets, One Hot Encoding: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Word: sat, One Hot Encoding: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Word: the, One Hot Encoding: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


### Terapkan ke Data

In [ ]:
words = [word.lower().strip(string.punctuation) for word in data_tokenized]
vocabulary = sorted(set(words))

encoder = OneHotEncoder(sparse_output=False)
one_hot_vectors = encoder.fit_transform(np.array(vocabulary).reshape(-1, 1))

word_to_onehot = {vocabulary[i]: one_hot_vectors[i] for i in range(len(vocabulary))}

for word, vector in list(word_to_onehot.items())[:10]:
    print(f"Word: {word}, One Hot Encoding: {vector}")

###

## Bag Of Words

### Example

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "Cats and dogs are pets."
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 0 1 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 0 0 0 1 0 0]]
['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']


### Terapkan ke Data Tokenized

In [35]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform([" ".join(data_tokenized[:20])])

print(X.toarray())
print(vectorizer.get_feature_names_out())

[[2 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 1]]
['alice' 'bank' 'beginning' 'book' 'conversations' 'get' 'nothing'
 'peeped' 'pictures' 'reading' 'sister' 'sitting' 'thought' 'tired'
 'twice' 'use' 'without']


## TF-IDF

### Example

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "Cats and dogs are pets."
]

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(documents)

print(X_tfidf.toarray())
print(tfidf_vectorizer.get_feature_names_out())

[[0.         0.         0.42755362 0.         0.         0.
  0.         0.42755362 0.32516555 0.         0.32516555 0.6503311 ]
 [0.         0.         0.         0.         0.42755362 0.
  0.42755362 0.         0.32516555 0.         0.32516555 0.6503311 ]
 [0.4472136  0.4472136  0.         0.4472136  0.         0.4472136
  0.         0.         0.         0.4472136  0.         0.        ]]
['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']


### Data Tokenized

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform([" ".join(data_tokenized[:20])])

print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0.39223227 0.19611614 0.19611614 0.39223227 0.19611614 0.19611614
  0.19611614 0.19611614 0.19611614 0.19611614 0.39223227 0.19611614
  0.19611614 0.19611614 0.19611614 0.19611614 0.19611614]]
['alice' 'bank' 'beginning' 'book' 'conversations' 'get' 'nothing'
 'peeped' 'pictures' 'reading' 'sister' 'sitting' 'thought' 'tired'
 'twice' 'use' 'without']


## Count Vectorizer

### Example

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "Cats and dogs are pets."
]

count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(documents)

print(X_count.toarray())
print(count_vectorizer.get_feature_names_out())

[[0 0 1 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 0 0 0 1 0 0]]
['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']


### Data Tokenized

In [39]:
count_vectorizer = CountVectorizer()
X = count_vectorizer.fit_transform([" ".join(data_tokenized[:20])])

print(X.toarray())
print(count_vectorizer.get_feature_names_out())

[[2 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 1]]
['alice' 'bank' 'beginning' 'book' 'conversations' 'get' 'nothing'
 'peeped' 'pictures' 'reading' 'sister' 'sitting' 'thought' 'tired'
 'twice' 'use' 'without']
